@startuml Use-Case Diagram
:User:
:Customer:
:Admin:

Admin <|-- User
Customer <|-- User

package pos{
Customer --> (authenticate)
Customer --> (place order)
Customer --> (track order)

Admin --> (authenticate)
Admin --> (update order status)
(update order status) .. (track order) : includes
Admin --> (update products catalog)
}
@enduml