@startuml Use-Case Diagram

:Customer: --> (authenticate)
:Customer: --> (place order)
(place order) -..> (track order)

:Admin: --> (authenticate)
:Admin: --> (update order status)
:Admin: --> (update products catalog)

@enduml