@startuml Use-Case Diagram
:User:
:Admin:
:Customer:

User <|-- Admin
User <|-- Customer

package OrderManager{
Admin --> (authenticate)
Admin --> (update order status)
Admin --> (update products catalog)

Customer --> (sign up)
Customer --> (login)
Customer --> (place order)
Customer --> (track order)
}
@enduml